# Generated by Django 3.2.6 on 2021-08-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_changepasswordrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePasswordRequest',
        ),
    ]
